stages:
  - install

install-grafana:
  stage: install
  image:
    name: alpine/helm:3.20.2
  before_script:
    - mkdir -p ~/.kube
    - echo -n $KUBE_CONFIG_B64 | base64 -d > ~/.kube/config
  script:
    - helm upgrade --install grafana ./infra/monitoring/grafana/grafana-chart --atomic --timeout 15m
  after_script:
    - rm -f ~/.kube/config