apiVersion: v1
kind: ServiceAccount
metadata:
  name: momo-user
  namespace: momo-app
---
apiVersion: v1
kind: Secret
metadata:
  name: momo-token
  namespace: momo-app
  annotations:
    kubernetes.io/service-account.name: momo-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: momo-binding
  namespace: momo-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  - kind: ServiceAccount
    name: momo-user
    namespace: momo-app